import { Poppins } from "next/font/google"
import Header from "./components/Header"
import "./globals.css"

const poppins = Poppins({
  weight: ["300", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: "Imam furniture",
  description: "Generated by Imam Furniture Mart",
  keywords:
    "imam furniture, imam furniture mart, imam furniture house, imam bed, imam cabinet, imam sokes, imam almirah, imam sofa, imam dining, imam interior",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="night" lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
